### ISSUE TITLE
Tag Schema version

### ISSUE THREAD

**Issue by jracusin** [nasa-gcn/gcn.nasa.gov#975]
- [x] remove schema not in production nasa-gcn/gcn-schema#96
- [x] schema must validate
- [x] replace most of anyOf with allOf nasa-gcn/gcn-schema#95
- [x] change references to cite by topic:timestamp or circular:circID nasa-gcn/gcn-schema#98
- [x] remove early warning & preliminary from alert_type - change to string with "initial, update, retraction" as examples nasa-gcn/gcn-schema#93
- [ ] need record somehow to include tag of schema

**Comment by dakota002** [comment]
Tagging convention that may leave room for specific updates
 ex: gcn-schema-v1, 
Tag rerouting 
  gcn.nasa.gov/schema/latest, gcn.nasa.gov/schem/main, gcn.nasa.gov/schem/gcn-schema-v1, etc

**Comment by dakota002** [comment]
1st checkbox : https://github.com/nasa-gcn/gcn-schema/pull/95

**Comment by dakota002** [comment]
@jracusin which files need to be untracked in main, the fermi folder?

**Comment by lpsinger** [comment]
@jracusin, in the future, this kind of checklist would work better as a milestone.

**Comment by lpsinger** [comment]
Done long ago, now.
